# Generated by Django 4.2.6 on 2023-10-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmw_description', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesdescription',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
